#!/usr/bin/env bash

set -ex # exit on error, echo commands

echo "--- Update rosdep"
rosdep update

echo "source /usr/share/gazebo/setup.sh" >> ~/.bashrc
echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc
source /usr/share/gazebo/setup.sh
source /opt/ros/noetic/setup.bash

echo "--- Cloning and installing Clover packages"
mkdir -p $HOME/catkin_ws/src
git clone --depth 1 https://github.com/CopterExpress/clover $HOME/catkin_ws/src/clover
git clone --depth 1 https://github.com/CopterExpress/ros_led $HOME/catkin_ws/src/ros_led
git clone --depth 1 https://github.com/ethz-asl/mav_comm $HOME/catkin_ws/src/mav_comm

# Make PX4 and Gazebo plugins visible in the workspace
ln -s $HOME/PX4-Autopilot $HOME/catkin_ws/src/PX4-Autopilot
ln -s $HOME/PX4-Autopilot/Tools/sitl_gazebo $HOME/catkin_ws/src/sitl_gazebo

rosdep install --from-paths $HOME/catkin_ws/src --ignore-src --rosdistro $ROS_DISTRO -y

sudo /opt/ros/noetic/lib/mavros/install_geographiclib_datasets.sh
/usr/bin/python3 -m pip install -r $HOME/catkin_ws/src/clover/clover/requirements.txt

cd ${HOME}/catkin_ws && catkin_make

echo "source ${HOME}/catkin_ws/devel/setup.bash" >> ~/.bashrc
source ${HOME}/catkin_ws/devel/setup.bash

echo "--- Adding Clover vehicle startup script to PX4"
ln -s "$(catkin_find clover_simulation airframes)"/* $HOME/PX4-Autopilot/ROMFS/px4fmu_common/init.d-posix/airframes/

echo "--- Exposing examples"
ln -s ${HOME}/catkin_ws/src/clover/clover/examples ${HOME}/
[[ -d ${HOME}/examples ]] # test symlink is valid
