#!/usr/bin/env bash

set -ex # exit on error, echo commands

sudo apt-get install -y libjansson-dev libboost-dev imagemagick libtinyxml-dev mercurial cmake build-essential curl
sudo apt install python-is-python2
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
export NVM_DIR=$HOME/.nvm
source $NVM_DIR/nvm.sh
nvm install 8
git clone https://github.com/osrf/gzweb && cd ~/gzweb && git checkout gzweb_1.4.1
source /usr/share/gazebo/setup.sh
export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:$HOME/catkin_ws/src/clover/clover_simulation/models
npm run deploy --- -m
# HACK: make Clover's URDF assets accesible (.dae model files)
ln -s ~/catkin_ws/src/clover/clover_description/ http/client/assets/
